stages:
  - deploy

deploy-to-vercel:
  stage: deploy
  image: node:13.10.1-alpine3.10

  script:
    - npm i vercel
    - DEPLOYMENT_URL=$(./node_modules/.bin/vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN)
    # promote to the vercel's production
    - ./node_modules/.bin/vercel --prod -t $VERCEL_TOKEN